# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instagram_MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instagram_MVVM
pod 'IQKeyboardManagerSwift'
# add pods for desired Firebase products
 pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
end
